services:
  microwarp:
    image: ghcr.io/ccbkkb/microwarp:latest
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    ports:
      - "8080:8080"
    volumes:
      - warp-data:/etc/wireguard

  app:
    build: .
    command: bash start.sh
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    volumes:
      - ./config.py:/usr/src/app/config.py:ro
      - ./accounts:/usr/src/app/accounts
      - ./downloads:/usr/src/app/downloads
    network_mode: "service:microwarp"

volumes:
  warp-data:
